### ISSUE TITLE
可以说下关于riverpod的看法吗

### ISSUE THREAD

**Issue by lhlyu** [shaoting0730/Flutter_learn_demo#1]
[riverpod](https://riverpod.dev/docs/getting_started/)

**Comment by shaoting0730** [comment]
个人愚见~状态管理库实在太多了，其实都大差不差的，看个人爱好而已，也没有孰优孰劣，更多的只是看团队用的多不多。

**Comment by shaoting0730** [comment]
https://mp.weixin.qq.com/s/6mp0uXx5dsb1X0DeyYUqww  riverpod 挺不错的，再再再再再再再学一次。
